//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int f_sn { get; set; }
        public string f_class { get; set; }
        public string f_content { get; set; }
        public System.DateTime f_date { get; set; }
        public bool f_checked { get; set; }
    
        public virtual feedback_class feedback_class { get; set; }
    }
}
