//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGroup.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaHospital))]
    public partial class hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]        
        public hospital()
        {
            this.schedule = new HashSet<schedule>();
        }
    
        public string hos_id { get; set; }
        public string hos_name { get; set; }
        public string hos_eng_name { get; set; }
        public string hos_address { get; set; }
        public string hos_phone { get; set; }
        public bool hos_display { get; set; }
        public int c_id { get; set; }
        public int d_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule> schedule { get; set; }
    }
}
