//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGroup.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Metadataingrediant))]
    
    public partial class ingrediant
    {
        public string ing_id { get; set; }
        public string ing_name { get; set; }
        public string ing_eng_name { get; set; }
        public string ing_category { get; set; }
        public string ing_restricted { get; set; }
        public string ing_limitation { get; set; }
    }
}
