//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGroup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project2Entities : DbContext
    {
        public Project2Entities()
            : base("name=Project2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrator { get; set; }
        public virtual DbSet<announcement> announcement { get; set; }
        public virtual DbSet<bodypart> bodypart { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<feedback_class> feedback_class { get; set; }
        public virtual DbSet<hospital> hospital { get; set; }
        public virtual DbSet<ingrediant> ingrediant { get; set; }
        public virtual DbSet<no_alarm> no_alarm { get; set; }
        public virtual DbSet<no_dur_cont> no_dur_cont { get; set; }
        public virtual DbSet<no_dur_enddate> no_dur_enddate { get; set; }
        public virtual DbSet<no_freq_active_pause> no_freq_active_pause { get; set; }
        public virtual DbSet<no_freq_day> no_freq_day { get; set; }
        public virtual DbSet<no_freq_hour> no_freq_hour { get; set; }
        public virtual DbSet<no_freq_time> no_freq_time { get; set; }
        public virtual DbSet<no_freq_week> no_freq_week { get; set; }
        public virtual DbSet<notification> notification { get; set; }
        public virtual DbSet<schedule> schedule { get; set; }
        public virtual DbSet<symptom> symptom { get; set; }
        public virtual DbSet<dep_sym_ref> dep_sym_ref { get; set; }
    }
}
