//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class no_freq_week
    {
        public int freq_sn { get; set; }
        public bool no_mon { get; set; }
        public bool no_tue { get; set; }
        public bool no_wed { get; set; }
        public bool no_thu { get; set; }
        public bool no_fri { get; set; }
        public bool no_sat { get; set; }
        public bool no_sun { get; set; }
        public int no_sn { get; set; }
    }
}
