//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public long sn { get; set; }
        public string doc_id { get; set; }
        public string dep_id { get; set; }
        public string hos_id { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public bool s_display { get; set; }
    
        public virtual department department { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual hospital hospital { get; set; }
    }
}
